import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import CssBaseline from '@mui/material/CssBaseline';
import GlobalStyles from '@mui/material/GlobalStyles';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Order Management",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={`${inter.className}`}>
    <Providers>
     <CssBaseline />
     {children}
    </Providers>
   </body>
  </html>
 );
}
